### ISSUE TITLE
Messing category wikitext

### ISSUE THREAD

**Issue by AndySky21** [middlebury/CategorySuggest#14]
In my project I'm using $wgDefaultUserOptions['forceeditsummary'] = 1. Edit page reloads if no summary is provided.
When this happens, categories mess up badly. 
1. The Category link wikitext appears in the reloaded page, below the title, separated by a whitespace.
2. They also appear in the textarea itself, though, and they are not stripped by the script.
3. Finally they also appear in the CategorySuggest inputbox. They're present in the script source code as value for the input, so it isn't the browser trying to autofill a form.
This means that, apart from the graphical issue caused by [1], if the page is saved without changing either the textarea or the input, categories are present twice. This can be seen when editing again, as category names are present twice in the input box.

**Comment by adamfranco** [comment]
hmm... I've never used that option before. I'm busy with other projects for a short while, but if you can figure out a fix before I have a chance to loop back around on this I'd be happy to review it.

**Comment by AndySky21** [comment]
As I saw it, it's my responsibility now.
Luckily the material is well documented in comments, so I can handle it.
I'll try something soon.

**Comment by AndySky21** [comment]
Fixed. Closing issue.
