### ISSUE TITLE
Capitalizing first letters of categories: unnecessary when $wgCapitalLinks = false

### ISSUE THREAD

**Issue by bogota** [middlebury/CategorySuggest#21]
CategorySuggest always capitalizes the first letters of category names shown up in the article's input box. https://github.com/middlebury/CategorySuggest/blob/master/CategorySuggest.body.php#L197

The behavior can mess up category links if the article has category names beginning with lowercases in the circumstance where $wgCapitalLinks or $wgCapitalLinkOverrides is set to false to allow usage of such names.

**Comment by stevengnelson** [comment]
Thanks for reporting this issue, it is now resolved.
