### ISSUE TITLE
Italian and Spanish translations

### ISSUE THREAD

**Issue by adamfranco** [middlebury/CategorySuggest#24]
From: Manuel Blasco Felip

I just deployed the new version, I guess have to wait for the server to refresh with it.
But so far so good.
Jus a couple of questions...

I seen, maybe, a mistake in the italian translation, there is a \ and a ' in the middle of the text?!?!

Also i did my best to add an spanish one too, in case you want to use it.
Here it is, but i am not sure about the meaning of the long fields, specially the last one.

     'it' => array(
       'categorysuggest-title' => 'ASSEGNAZIONE CATEGORIE',
       'categorysuggest-subtitle' => 'Digitare il nome di una categoria per questo articolo.',
       'categorysuggest-boxlabel' => 'Categorie',
       'categorysuggest-taglabel' => 'Categorie piÃ¹ utilizzate',
       'categorysuggest-select' => 'Clicca per aggiungere la categoria all\'elenco per questa pagina!'
    )
    'es' => array(
       'categorysuggest-title' => 'ASIGNACIÓN DE CATEGORIA',
       'categorysuggest-subtitle' => 'Introduzca el nombre de una categoría para este artículo por favor.',
       'categorysuggest-boxlabel' => 'Categoría',
       'categorysuggest-taglabel' => 'Categorías populares',
       'categorysuggest-select' => 'Pinche aquí para añadir una categoría de la lista a la pagina!'
    )

Regards,
Manu

**Comment by stevengnelson** [comment]
Thanks Manu, this has been resolved.

**Comment by AndySky21** [comment]
The \' in Italian translation is to escape the ', as it is used to quote the string.
