### ISSUE TITLE
Can't search words that are not at the start -> suggested fix -> a visual bug results

### ISSUE THREAD

**Issue by JamesGatesRichardson** [middlebury/CategorySuggest#26]
Hello,

I like your extension!  I am setting up a new wiki and an old extension no longer works (SelectCategoryTagCloud).  The tag cloud really is what did it for me =)  

Your extension is the best I've found!  I tweaked the code a little to get the last peice of functionality I could need. I wanted to share that with you and bring up a visual bug that results from it.

In categorySuggest.php, I changed line 74 (the preg_replace() to the following:
$searchString = preg_replace('/^\s*LIKE\s\'*/', '\'%', $searchString);

the \' in the first parameter and \'% in the 2nd is what enabled it.

now I can search in the middle of a category name if I wanted.  It flows through to the front end correctly.  the visual bug is that it highlights the first X characters even if the match is the 2nd word.

keep up the good work!

Thanks!

**Comment by stevengnelson** [comment]
Thanks for reporting this and providing your change. I've implemented this feature as well as fixing the visual bug that comes along with it.

**Comment by JamesGatesRichardson** [comment]
Exciting!

Thank you,

James

On Tue, Feb 23, 2016 at 4:00 PM, Steven Nelson <notifications@github.com>
wrote:

> Thanks for reporting this and providing your change. I've implemented this
> feature as well as fixing the visual bug that comes along with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/middlebury/CategorySuggest/issues/26#issuecomment-187934818>
> .
>



-- 
Thank you for your time,

James
