### ISSUE TITLE
Category suggestion no longer working after upgrade to MediaWiki 29.0

### ISSUE THREAD

**Issue by andywrightoz** [middlebury/CategorySuggest#29]
I upgraded to MediaWiki 29.0 and now the suggest category is no longer working - i.e no longer showing the list of suggestions when I start typing something into the Category Assignment box . 

FYI I've compared it to a working version in MediaWiki 28.0, and I'm now getting the following console errors, if this helps you. Keep up the great work - this is a really cool extension :-)  

[Warning] This page is using the deprecated ResourceLoader module "jquery.ui.widget".
[Warning] This page is using the deprecated ResourceLoader module "jquery.ui.position".
[Warning] This page is using the deprecated ResourceLoader module "jquery.ui.core".
Please use "mediawiki.ui.button" or "oojs-ui" instead.
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (index.php, line 0) https://URL./?action=ajax&rs=fnCategorySuggestAjax&rsargs%5B%5D=P

When I click on the error URL - I'm not a programmer but maybe the SQL in the code needs changing to reflect a potential database schema update ?

_A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
_Query: SELECT DISTINCT cl_to FROM `categorylinks` WHERE UCASE(CONVERT(cl_to USING utf8)) LIKE UCASE('%P%' ESCAPE '`' ) LIMIT 50_ 
_Function: fnCategorySuggestAjax
_Error: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''`' ) LIMIT 50' at line 1 (localhost)___

**Comment by cg923** [comment]
Thanks for this report, this should work now.

Released a new 1.9 tag with this fix.

**Comment by andywrightoz** [comment]
Hey Corey - I really appreciate your help here - I've just tried it in MediaWiki 19.1 and it works great and will save me heaps of time - you're a legend ! There's another bit of functionality which hasn't been working for a while, which I'll raise as a new issue. Thanks once again !

**Comment by cg923** [comment]
So glad you found it helpful!  Hopefully we can get the next issue sorted out soon too.  Thanks again for the contributions.
