### ISSUE TITLE
Issue with SMW:PageForms

### ISSUE THREAD

**Issue by johnleeshore** [middlebury/CategorySuggest#31]
CategorySuggest seems to create an error when you save a form with a predetermined category use PageForms:

PHP Notice:  Undefined index: txtSelectedCategories in ..extensions/CategorySuggest/CategorySuggest.body.php on line 80.

There is no error generated saving pages not linked to PageForms

Presume this is the same issue as with Extension:CreateRedirect and Extension:MassEditRegex

**Comment by cg923** [comment]
Hi John.  I just looked into this and it is easy enough to suppress the error. As we don't have PageForms installed anywhere, it's hard for me to check this out further without a bunch of legwork.  Is there any actual poor behavior as a result of this error?  Like, is data not being saved?  Or is simply displaying a non-page-breaking message?

**Comment by johnleeshore** [comment]
Data is saved. Just shows the error. Not sure it’s that important but was just putting it out there.

**Comment by cg923** [comment]
Ok, then it's a simple fix.  Thanks for pointing it out John!
