### ISSUE TITLE
MySQL username/password error.  Not sure what to do.

### ISSUE THREAD

**Issue by gbell12** [middlebury/CategorySuggest#6]
I receive the attached error during completion.  There's nothing in the installation instructions about setting a username/password in the settings for CategorySuggest.

![screenshot from 2013-06-25 08 46 06](https://f.cloud.github.com/assets/3937658/699571/223bdd3c-dd21-11e2-9341-f06aa9b6e0d4.png)

**Comment by defconzx** [comment]
Confirmed that this has fixed the issue. Thanks alot!
