### ISSUE TITLE
Suggests all categories, regardless of match

### ISSUE THREAD

**Issue by ismay** [middlebury/CategorySuggest#9]
CategorySuggest works fine after installing, but it returns all categories when typing in the input box (regardless of whether they match the input or not).

I've checked the GET request, and that seems to be working fine. What I did see was a js error, which might be the source of this behaviour (I don't know):

```
Use of "sajax_debug_mode" is deprecated. Sajax is deprecated, use jQuery.ajax or mediawiki.api instead.
```

Any idea what's causing this bug?

**Comment by adamfranco** [comment]
Hi Ismay, I've recently made a number of improvements to this plugin. Could you test again on the most recent master version ( https://github.com/middlebury/CategorySuggest/archive/master.zip ) and confirm whether or not the new version still has this problem? Thanks!

**Comment by ismay** [comment]
Hi Adam, unfortunately I'm not using mediawiki anymore, so I haven't got anything to test this with, otherwise I'd be happy to test it for you!

**Comment by adamfranco** [comment]
Thanks for responding, @ismay . I'll close this issue for now.
